# Generated by Django 4.1.5 on 2023-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comm', '0004_rename_image_product_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default='', upload_to='static/images/', verbose_name='Document'),
        ),
    ]
