# Generated by Django 4.1.5 on 2023-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comm', '0006_remove_product_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='p_img_1',
        ),
        migrations.AddField(
            model_name='product',
            name='p_img_2',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_img_3',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_img_4',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
