# Generated by Django 4.1.5 on 2023-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comm', '0008_product_p_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_slug',
            field=models.SlugField(default=''),
        ),
    ]
